# Generated by Django 2.2.6 on 2019-12-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='tag',
            field=models.CharField(default='Dog-1', help_text="Non-unique identifier for the dog, on the form 'Dog-%d'", max_length=16),
        ),
    ]
