# Generated by Django 2.2.3 on 2019-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='predators', to='tests.Mice'),
        ),
        migrations.AddField(
            model_name='dog',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to='tests.Mice'),
        ),
    ]
