# Generated by Django 2.2.6 on 2019-12-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_dog_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(choices=[('LABRADOR', 'Labrador'), ('HUSKY', 'Husky'), ('BULLDOG', 'BULLDOG'), ('FLATCOAT', 'Flatcoat retriever'), ('MALAMUTE', 'Alaskan Malamuate')], default='LABRADOR', max_length=16),
            preserve_default=False,
        ),
    ]
