# Generated by Django 2.2.3 on 2019-07-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20190718_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mice',
            new_name='Mouse',
        ),
    ]
