# Generated by Django 2.2.6 on 2019-12-10 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_dog_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mice', to=settings.AUTH_USER_MODEL),
        ),
    ]
