# Generated by Django 2.2.6 on 2020-05-14 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_mouse_keeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=32)),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='tests.Dog')),
            ],
        ),
    ]
