# Generated by Django 2.2.6 on 2021-01-02 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_dog_bark_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dog',
            unique_together={('owner', 'tag')},
        ),
    ]
