# Generated by Django 2.2.27 on 2022-03-13 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20210102_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatUserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.BooleanField(default=False)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_user_relations', to='tests.Cat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_user_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cat', 'user')},
            },
        ),
        migrations.AddField(
            model_name='cat',
            name='user_relations',
            field=models.ManyToManyField(blank=True, related_name='related_to_cats', through='tests.CatUserRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
