from django.conf import settings

OPERATION_UPDATE = "update"
OPERATION_DELETE = "delete"
OPERATION_CREATE = "create"
OPERATION_UPSERT = "upsert"

USE_ID_SUFFIXES_FOR_FK_SETTINGS_KEY = "GRAPHENE_DJANGO_CUD_USE_ID_SUFFIXES_FOR_FK"
USE_ID_SUFFIXES_FOR_M2M_SETTINGS_KEY = "GRAPHENE_DJANGO_CUD_USE_ID_SUFFIXES_FOR_M2M"
